cask_args appdir: '~/Applications'

# Development tools
mas "Xcode", id: 497799835
cask "sf-symbols"

# Browsers
cask "google-chrome"

# Work
#mas "Things3", id: 904280696
mas "Pages", id: 409201541
mas "Numbers", id: 409203825
mas "Keynote", id: 409183694
mas "Pixelmator", id: 407963104

# "Social" stuff
mas "Tweetbot", id: 1384080005
mas "Slack", id: 803453959

# Utilities
cask "airbuddy", args: { appdir: "~/Applications/Utilities" }
cask "choosy", args: { appdir: "~/Applications/Utilities" }
mas "1Blocker", id: 1365531024
cask "mailtrackerblocker"
